-- PostgreSQL schema for the Lost and Found Management System.

CREATE TYPE user_role AS ENUM ('user', 'admin');
CREATE TYPE item_status AS ENUM ('open', 'matched', 'claimed', 'resolved', 'archived');
CREATE TYPE match_status AS ENUM ('suggested', 'reviewed', 'confirmed', 'rejected');
CREATE TYPE claim_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE notification_type AS ENUM ('match', 'claim', 'system');

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role user_role NOT NULL DEFAULT 'user',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lost_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    category VARCHAR(80) NOT NULL,
    location VARCHAR(150) NOT NULL,
    date_lost DATE NOT NULL,
    image_filename VARCHAR(255),
    status item_status NOT NULL DEFAULT 'open',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_lost_items_title_length CHECK (char_length(title) > 2)
);

CREATE TABLE found_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    category VARCHAR(80) NOT NULL,
    location VARCHAR(150) NOT NULL,
    date_found DATE NOT NULL,
    image_filename VARCHAR(255),
    status item_status NOT NULL DEFAULT 'open',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_found_items_title_length CHECK (char_length(title) > 2)
);

CREATE TABLE item_matches (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lost_item_id INTEGER NOT NULL REFERENCES lost_items(id) ON DELETE CASCADE,
    found_item_id INTEGER NOT NULL REFERENCES found_items(id) ON DELETE CASCADE,
    score NUMERIC(5,2) NOT NULL,
    reasons TEXT NOT NULL,
    status match_status NOT NULL DEFAULT 'suggested',
    notifications_sent BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_item_matches_pair UNIQUE (lost_item_id, found_item_id)
);

CREATE TABLE claims (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claimant_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    found_item_id INTEGER NOT NULL REFERENCES found_items(id) ON DELETE CASCADE,
    lost_item_id INTEGER REFERENCES lost_items(id) ON DELETE SET NULL,
    proof_text TEXT NOT NULL,
    supporting_image VARCHAR(255),
    status claim_status NOT NULL DEFAULT 'pending',
    admin_notes TEXT,
    reviewed_by_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_claims_proof_length CHECK (char_length(proof_text) >= 10)
);

CREATE TABLE notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    type notification_type NOT NULL DEFAULT 'system',
    related_url VARCHAR(255),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_lost_items_title ON lost_items (title);
CREATE INDEX idx_lost_items_category ON lost_items (category);
CREATE INDEX idx_lost_items_location ON lost_items (location);
CREATE INDEX idx_lost_items_date_lost ON lost_items (date_lost);
CREATE INDEX idx_found_items_title ON found_items (title);
CREATE INDEX idx_found_items_category ON found_items (category);
CREATE INDEX idx_found_items_location ON found_items (location);
CREATE INDEX idx_found_items_date_found ON found_items (date_found);
CREATE INDEX idx_item_matches_score ON item_matches (score DESC);
CREATE INDEX idx_claims_status ON claims (status);
CREATE INDEX idx_notifications_user_read ON notifications (user_id, is_read);
